spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:cadastros-basicos
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    hostname: localhost
    ip-address: "*"
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka/