spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cadastros-basicos
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
eureka:
  instance:
    hostname: localhost
    ip-address: "*"
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka/